#!/usr/bin/env python3
#
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generates PruneKernels.gramMmaPacked (paste the output into PruneKernels.java): PruneKernels.gramMma over packed FP16 vectors (two halves per int, low =
even dimension), split by rows into SHARDS IntArrays so that more than Integer.MAX_VALUE halves fit (TornadoVM
arrays are int-indexed). The A operand is staged with one plain load per word; the B operand extracts halves."""
ROWS = 96          # slots
RB = ROWS // 16    # row blocks = warps
CB = ROWS // 8     # column blocks = fragments per warp
SHARDS = 4
o = []
w = o.append


def load(var, row, word):
    lines = [f'int {var} = 0;', f'if (ids[{row}] >= 0) {{', f'    int at = base[{row}] + {word};']
    for i in range(SHARDS):
        if i == 0:
            lines.append(f'    if (shard[{row}] == 0) {{')
        elif i < SHARDS - 1:
            lines.append(f'    }} else if (shard[{row}] == {i}) {{')
        else:
            lines.append('    } else {')
        lines.append(f'        {var} = s{i}.get(at);')
    lines += ['    }', '}']
    return lines


shard_params = ', '.join(f'IntArray s{i}' for i in range(SHARDS))
w(f'''    /**
     * The {ROWS} x {ROWS} Gram matrix of every node's candidates, with tensor cores ({{@code mma.sync m16n8k16}},
     * FP16 inputs, FP32 accumulation). Work-group {{@code b}} ({RB} warps) handles node {{@code b}}: each 16-dimension
     * slice of its candidates is staged once in shared memory as both the A operand (rows) and the B operand (the
     * same rows, transposed), and warp {{@code w}} accumulates rows {{@code 16w..16w+15}} against all {CB} column
     * blocks.
     * <p>
     * Vectors are packed FP16 ({{@link PackedVectors}}): row {{@code id}} lives in shard {{@code id / rowsPerShard}} as
     * {{@code dim / 2}} words of two halves (low = even dimension), so the A operand is staged with one plain load per
     * word. Generated by {{@code codegen/gen_gram_mma_packed.py}}.
     */
    public static void gramMmaPacked(KernelContext ctx, {shard_params}, IntArray candIds, IntArray params, FloatArray gram) {{
        int b = ctx.groupIdx;
        int lid = ctx.localIdx;
        int warp = lid / 32;
        int dim = params.get(P_DIM);
        int words = dim / 2;
        int rowsPerShard = params.get(P_ROWS_PER_SHARD);
        int[] aForm = ctx.allocateIntLocalArray({ROWS * 8});
        int[] bForm = ctx.allocateIntLocalArray({CB * 64});
        int[] ids = ctx.allocateIntLocalArray({ROWS});
        int[] shard = ctx.allocateIntLocalArray({ROWS});
        int[] base = ctx.allocateIntLocalArray({ROWS});
        if (lid < {ROWS}) {{
            int id = candIds.get(b * {ROWS} + lid);
            ids[lid] = id;
            int s = 0;
            int local = 0;
            if (id >= 0) {{
                s = id / rowsPerShard;
                local = (id - s * rowsPerShard) * words;
            }}
            shard[lid] = s;
            base[lid] = local;
        }}
        ctx.localBarrier();''')
for c in range(CB):
    w(f'        float[] f{c} = ctx.mmaFragment(0.0f);')
w(f'''        int aOffset = warp * 16 * 8 * 4;
        for (int k0 = 0; k0 < dim; k0 += 16) {{
            int w0 = k0 / 2;
            for (int e = lid; e < {ROWS} * 8; e += {RB * 32}) {{
                int r = e / 8;
                int p = e % 8;''')
for line in load('v', 'r', 'w0 + p'):
    w('                ' + line)
w(f'''                aForm[r * 8 + p] = v;
            }}
            for (int e = lid; e < {CB} * 64; e += {RB * 32}) {{
                int c = e / 64;
                int kr = (e % 64) / 4;
                int jp = e % 4;
                int j0 = c * 8 + 2 * jp;
                int j1 = j0 + 1;
                int word = w0 + kr / 2;
                int shift = (kr % 2) * 16;''')
for line in load('v0', 'j0', 'word'):
    w('                ' + line)
for line in load('v1', 'j1', 'word'):
    w('                ' + line)
w('''                bForm[e] = ((v0 >>> shift) & 0xFFFF) | (((v1 >>> shift) & 0xFFFF) << 16);
            }
            ctx.localBarrier();
            HalfFloat[] fa = ctx.mmaLoadA(aForm, 16, aOffset);''')
for c in range(CB):
    w(f'            f{c} = ctx.mma(fa, ctx.mmaLoadB(bForm, 16, {c * 64 * 4}), f{c}, MMAShape.M16N8K16);')
w(f'''            ctx.localBarrier();
        }}
        int row = b * {ROWS} + warp * 16;''')
for c in range(CB):
    w(f'        ctx.mmaStore(f{c}, gram, row, {c * 8}, {ROWS});')
w('    }')
print('\n'.join(o))
